#################### Deployment ####################
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: opportunites-deployment
  labels:
    app: opportunites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opportunites
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opportunites
    spec:
      containers:
      - name: opportunites-container
        image: registry.gitlab.com/gitlabodix/cvtheque-opportunites-ms-prod
        args: ["--spring.profiles.active=prod"]
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
#################### Service ####################
---
apiVersion: v1
kind: Service
metadata:
  name: opportunites-ms
spec:
  selector:
    app: opportunites
  ports:
    - port: 8002
      targetPort: 8002

